apiVersion: v1
kind: Service
metadata:
  name: model
spec:
  selector:
    app: model
  ports:
    - protocol: TCP
      port: 8000        # internal service port
      targetPort: 8000 # container FastAPI port
  type: ClusterIP
